# default config
baseurl = "https://www.notsodownandoutmom.com/"
languageCode = "en-us"
title = "The Not So Down and Out Mom"
theme = "parsa-hugo"
summaryLength = "10"
paginate = 6

# output
[outputs]
home = ["HTML", "RSS", "JSON"]

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/headroom/headroom.js"
[[params.plugins.js]]
link = "plugins/instafeed/instafeed.min.js"
[[params.plugins.js]]
link = "plugins/masonry/masonry.js"
[[params.plugins.js]]
link = "plugins/reading-time/readingTime.min.js"
[[params.plugins.js]]
link = "plugins/smooth-scroll/smooth-scroll.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search.js"

# navigation
[[menu.main]]
name = "Home"
url = ""
weight = 1
hasChildren = true

#  [[menu.main]]
#  parent = "Homepage"
#  name = "Homepage 1"
#  url = "homepage/home-1"

#  [[menu.main]]
#  parent = "Homepage"
#  name = "Homepage 2"
#  url = "homepage/home-2"

[[menu.main]]
name = "About"
url = "about"
weight = 2

#[[menu.main]]
#name = "Contact"
#url = "contact"
#weight = 3

# deult parameter
[params]
logo = "logos/crossarrows.png"
home = "Home"
# theme layout ( two layout is available, "1" and "2" )
layout = "2"
# Meta data
description = "This is meta description"
# Preloader
preloader = true
# search
search = true
# about author
author = "The Not So Down and Out Mom"
author_image = "images/banner-img.png"
bio = "A blog for parents on the special-needs journey!"
# Contact Form Action
contact_form_action = "#"
# Google Analitycs
google_analitycs_id = "Your ID"
# copyright
copyright = "Copyright &copy; 2020 a theme by [themefisher.com](themefisher.com)"

# Instagram feed
[params.instafeed]
enable = false
access_token = "IGQVJYeUk4YWNIY1h4OWZANeS1wRHZARdjJ5QmdueXN2RFR6NF9iYUtfcGp1NmpxZA3RTbnU1MXpDNVBHTzZAMOFlxcGlkVHBKdjhqSnUybERhNWdQSE5hVmtXT013MEhOQVJJRGJBRURn"

# cookies
[params.cookies]
enable = true
expire_days = 2

# social site
[[params.social]]
icon = "ti-facebook"
enable = false
url = "#"

#[[params.social]]
#icon = "ti-twitter-alt"
#enable = false
#url = "#"

#[[params.social]]
#icon = "ti-linkedin"
#enable = false
#url = "#"

#[[params.social]]
#icon = "ti-github"
#enable = false
#url = "#"

[deployment]
# By default, files are uploaded in an arbitrary order.
# Files that match the regular expressions in the "Order" list
# will be uploaded first, in the listed order.
order = [".jpg$", ".gif$"]


[[deployment.targets]]
# An arbitrary name for this target.
name = "mydeployment"
# The Go Cloud Development Kit URL to deploy to. Examples:
# GCS; see https://gocloud.dev/howto/blob/#gcs
# URL = "gs://<Bucket Name>"

# S3; see https://gocloud.dev/howto/blob/#s3
# For S3-compatible endpoints, see https://gocloud.dev/howto/blob/#s3-compatible
URL = "s3://www.notsodownandoutmom.com?region=us-east-1"
#URL = "s3://notsodownandoutmom.com?region=us-east-1"

# Azure Blob Storage; see https://gocloud.dev/howto/blob/#azure
# URL = "azblob://$web"

# You can use a "prefix=" query parameter to target a subfolder of the bucket:
# URL = "gs://<Bucket Name>?prefix=a/subfolder/"

# If you are using a CloudFront CDN, deploy will invalidate the cache as needed.
cloudFrontDistributionID = "EDJ1VKM3OJO14"

# Optionally, you can include or exclude specific files.
# See https://godoc.org/github.com/gobwas/glob#Glob for the glob pattern syntax.
# If non-empty, the pattern is matched against the local path.
# All paths are matched against in their filepath.ToSlash form.
# If exclude is non-empty, and a local or remote file's path matches it, that file is not synced.
# If include is non-empty, and a local or remote file's path does not match it, that file is not synced.
# As a result, local files that don't pass the include/exclude filters are not uploaded to remote,
# and remote files that don't pass the include/exclude filters are not deleted.
# include = "**.html" # would only include files with ".html" suffix
# exclude = "**.{jpg, png}" # would exclude files with ".jpg" or ".png" suffix


# [[deployment.matchers]] configure behavior for files that match the Pattern.
# Samples:

[[deployment.matchers]]
#  Cache static assets for 1 year.
pattern = "^.+\\.(js|css|svg|ttf)$"
cacheControl = "max-age=31536000, no-transform, public"
gzip = true

[[deployment.matchers]]
pattern = "^.+\\.(png|jpg)$"
cacheControl = "max-age=31536000, no-transform, public"
gzip = false

[[deployment.matchers]]
pattern = "^.+\\.(html|xml|json)$"
gzip = true